In [1]:
#import numpy
import numpy as np

In [2]:
#array one dimensional
a=[1,2,3,4,5]
#array two dimensional
b=[1,2,3,4],[5,6,7,8]

In [3]:
#array changing
arr= np.array(a)
brr=np.array(b)

In [4]:
brr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
type(arr)
type(brr)

numpy.ndarray

In [6]:
#ndim dimension of array
brr.ndim

2

In [7]:
b

([1, 2, 3, 4], [5, 6, 7, 8])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr[0]=500

In [10]:
a

[1, 2, 3, 4, 5]

In [11]:
np.copy(a)
a=arr
arr[0]=600

In [58]:
# error accor this function
#list(range(1,10,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [13]:
#0.4 varlues not take in the range function use np.arange
list(np.arange(0.4,10.4,1))

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [62]:
# sample data set of an 15 data point to preparing
list(np.linspace(1,5,10))

[1.0,
 1.4444444444444444,
 1.8888888888888888,
 2.333333333333333,
 2.7777777777777777,
 3.2222222222222223,
 3.6666666666666665,
 4.111111111111111,
 4.555555555555555,
 5.0]

In [15]:
#log of the particular things sample of an range
list(np.logspace(1,5,10))

[10.0,
 27.825594022071243,
 77.4263682681127,
 215.44346900318823,
 599.4842503189409,
 1668.100537200059,
 4641.588833612777,
 12915.496650148827,
 35938.13663804626,
 100000.0]

In [64]:
#assending of an zeros and ones
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
#arrray form ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
#array from
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
arr.shape

(5,)

In [21]:
arr.size

5

In [22]:
list3=np.random.randn(10)
print(list3)

[ 0.65714261 -1.06432468  0.17399703  0.32847587  0.55824988 -1.75009917
  0.19302931  1.67962666  0.53093253  0.10063237]


In [23]:
list1=np.random.rand(10)
list2=np.random.rand(10)

In [67]:
list1

array([0.39842053, 0.65051353, 0.24565354, 0.13731181, 0.92561001,
       0.35460697, 0.49452814, 0.06394038, 0.56477488, 0.55831465])

In [24]:
add=np.add(list1,list2)
print(add)

[0.69610973 0.6728745  0.97788429 0.53539405 1.78951697 0.82450427
 1.24844715 0.46896694 1.27244    0.72647243]


In [25]:
sub=np.subtract(list1,list2)
print(sub)

[ 0.10073133  0.62815256 -0.4865772  -0.26077042  0.06170305 -0.11529034
 -0.25939088 -0.34108618 -0.14289024  0.39015687]


In [26]:
mul=np.multiply(list1,list2)
print(mul)

[0.11860549 0.01454612 0.17987508 0.05466139 0.79964093 0.16662886
 0.37283416 0.02589755 0.39967148 0.09388495]


In [27]:
div=np.divide(list1,list2)
print(div)

[ 1.33837751 29.09146598  0.33548652  0.34493328  1.07142326  0.75464779
  0.65594332  0.15786713  0.79808212  3.32018324]


In [28]:
dot=np.dot(list1,list2)#dot function matrix multiply
print(dot)

2.226246009532818


In [29]:
np.sqrt(2)

1.4142135623730951

In [30]:
np.log(10)

2.302585092994046

In [31]:
np.abs(-1)# absolute values

1

In [32]:
np.power(2,2) #power root

4

In [33]:
np.min(list1)

0.06394038069815167

In [70]:
np.argmax(list1)# idexing of the maximum value min function also available

4

In [69]:
np.argmin(list1)

7

In [35]:
list4=np.random.rand(4,3)

In [36]:
np.shape(list4)

(4, 3)

In [37]:
np.reshape(list4,(6,2))#reshape the values shape function

array([[0.20781216, 0.1763565 ],
       [0.703951  , 0.21479163],
       [0.07406997, 0.1467455 ],
       [0.9809591 , 0.69414196],
       [0.38077276, 0.3978147 ],
       [0.58899653, 0.04109869]])

In [72]:
list5=np.random.rand(3,4,2)#3,first value 4,2 ismatrix
print(list5)

[[[0.80516891 0.25652025]
  [0.99717296 0.45587412]
  [0.07885287 0.14414149]
  [0.04775426 0.94314128]]

 [[0.39406774 0.32060916]
  [0.81789051 0.15420544]
  [0.26293394 0.47098875]
  [0.86453617 0.19656579]]

 [[0.31079908 0.30070358]
  [0.22678884 0.66346996]
  [0.15648595 0.00629375]
  [0.1396806  0.93596908]]]


In [39]:
a=[1,2,3,4,5]

In [40]:
ab=np.array(a)

In [41]:
a[0]

1

In [42]:
a[1:3]

[2, 3]

In [43]:
a[-1]

5

In [44]:
a[::-1]

[5, 4, 3, 2, 1]

In [45]:
l1=[1,2,3,4,5],[5,6,7,8,9],[1,3,5,7,9]

In [46]:
ac=np.array(l1)

In [47]:
ac

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [1, 3, 5, 7, 9]])

In [48]:
ac[:,3]#one dimensional values

array([4, 8, 7])

In [49]:
ac[1:,1:3] #two dimensional

array([[6, 7],
       [3, 5]])

In [50]:
ac[1:,3:5]

array([[8, 9],
       [7, 9]])

In [51]:
ac[:2,3:5]

array([[4, 5],
       [8, 9]])

In [52]:
ac.tolist() #tolist is the line wise view

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9], [1, 3, 5, 7, 9]]

In [53]:
# np.fromstring(ac.tostring())

In [54]:
ac.flatten() #flat array all are come in flat 1,2,3

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 1, 3, 5, 7, 9])